name: Screen capture by Puppeteer
author: Son Dao Thai (@sondt-1245)
description: Capture a screenshot of a webpage, element, area using Puppeteer
inputs:
  url:
    description: 'URL of the webpage to capture'
    required: true
  use-github-selector:
    description: 'Extract selector from commit message/ pull request comment. Use [[element: <selector>]] in commit message or comment "/screenshot [[element: <selector>]]" in PR to extract selector.'
    required: false
    default: 'false'
  selector:
    description: 'CSS selector of the element to capture'
    required: false
  output:
    description: 'Path to save the screenshot'
    required: false
    default: 'screenshot.png'
outputs:
  screenshot:
    description: 'Screenshot was captured and save at:'
    value: ${{ steps.setOutput.outputs.screenshot }}
  artifacts:
    description: 'Screenshot artifact URL:'
    value: ${{ steps.saveScreenshot.outputs.artifact-url }}

runs:
  using: 'composite'
  steps:

    # Because the action is triggered by issue_comment event, actions/checkout only checkout the code from the default branch.
    # We need to check out to the right PR's branch to capture the screenshot.
    - name: Github API Request
      if: ${{ github.event_name == 'issue_comment' }}
      id: request
      uses: octokit/request-action@v2.2.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Checkout to right branch
      if: ${{ github.event_name == 'issue_comment' }}
      uses: actions/checkout@v3
      with:
        token: ${{ github.token }}
        ref: ${{ fromJson(steps.request.outputs.data).head.ref }}

    - name: Extract selector from commit message
      id: extractSelector
      run: |
        if [[ "${{ inputs.use-github-selector }}" == "true" ]]; then
          export SELECTOR=$(echo "${{ github.event.head_commit.message }}" |  sed -n 's/.*\[\[element:\s*\([^]]*\)\]\].*/\1/p')
          [[ $SELECTOR ]] &&  echo "Selector was found from Github commit message: $SELECTOR"
        
          # Find selector from pull request comment body
          if [[ "${{ github.event.issue.pull_request }}" && '${{ github.event.comment.body }}' = /screenshot* ]]; then
            export SELECTOR=$(echo "${{ github.event.comment.body }}" |  sed -n 's/.*\[\[element:\s*\([^]]*\)\]\].*/\1/p')
        
            echo "Comment on pull request ${{ github.event.comment.body }}"
            [[ $SELECTOR ]] && echo "Selector was override from pull request comment body: $SELECTOR"
            echo "comment-selector=true" >> $GITHUB_OUTPUT
          fi
        else
          export SELECTOR="${{ inputs.selector }}"
          echo "Using selector from Github Action input: $SELECTOR"
        fi
        
        if [[ -z "$SELECTOR" ]]; then
          echo "Selector was not defined. We will capture the whole page."
        fi
        
        echo "selector=$(echo $SELECTOR)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install Node 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Puppeteer & process env
      shell: bash
      run: npm install puppeteer dotenv

    - name: Capture screenshot
      id: captureScreen
      shell: bash
      run: node ${{ github.action_path }}/capture.js || true
      env:
        ACTION_INPUTS_URL: ${{ inputs.url }}
        ACTION_INPUTS_SELECTOR: ${{ steps.extractSelector.outputs.selector }}
        ACTION_INPUTS_OUTPUT: ${{ inputs.output }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Save screenshot
      id: saveScreenshot
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: ${{ inputs.output }}

    - name: Set Output
      run: |
        echo "screenshot=$(echo ${{ inputs.output }})" >> $GITHUB_OUTPUT
      shell: bash

    - name: Update PR's comment
      if: ${{ steps.extractSelector.outputs.comment-selector == 'true' }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ github.event.comment.id }}
        body: "[screenshot archive](${{ steps.saveScreenshot.outputs.artifact-url }})"
        reactions: eyes

    - name: Github API Request
      if: ${{ github.event_name == 'issue_comment' }}
      uses: octokit/request-action@v2.2.0
      with:
        route: POST ${{ fromJson(steps.request.outputs.data).statuses_url }}
        state: ${{ job.status }}
        target_url: "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/${{ steps.saveScreenshot.outputs.artifact-id }}"
        context: "Screenshot / ${{ github.workflow }} (artifact)"
      env:
        GITHUB_TOKEN: ${{ github.token }}
