name: Puppeteer screen capture

on:
  push:
    branches-ignore: 
      - '**-patch-**'

  pull_request:

jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          directory: ${{ github.workspace }}
          port: 8080
          index-files: |
            ["index.html", "index.htm"]
          allowed-methods: |
            ["GET", "HEAD"]
          content-types: |
            {
              "appcache": "text/cache-manifest",
              "css": "text/css",
              "gif": "image/gif",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "txt": "text/plain",
              "xml": "text/xml"
            }
          log: "log.txt"
          logTime: "false"

      - name: Screenshot
        uses: ./.github/actions/puppeteer
        with:
          url: http://localhost:8080
          use-commit-message: 'true'
          selector: '.section-2 #button-3'
          output: 01_screenshot.png

