name: Puppeteer screen capture

on:
  issue_comment:
    types: [ created ]

jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sun-asterisk-research/puppeteer-play:latest
      options: --user root:root --cap-add=SYS_ADMIN
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && startsWith(github.event.comment.body , '/screenshot')) }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      # - name: Serve Files
      #   uses: Eun/http-server-action@v1
      #   with:
      #     directory: ${{ github.workspace }}
      #     port: 8080
      #     index-files: |
      #       ["index.html", "index.htm"]
      #     allowed-methods: |
      #       ["GET", "HEAD"]
      #     content-types: |
      #       {
      #         "appcache": "text/cache-manifest",
      #         "css": "text/css",
      #         "gif": "image/gif",
      #         "html": "text/html",
      #         "ico": "image/x-icon",
      #         "jpeg": "image/jpeg",
      #         "jpg": "image/jpeg",
      #         "js": "text/javascript",
      #         "json": "application/json",
      #         "png": "image/png",
      #         "txt": "text/plain",
      #         "xml": "text/xml"
      #       }
      #     log: "log.txt"
      #     logTime: "false"

      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.2.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Checkout to right branch
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ fromJson(steps.request.outputs.data).head.ref }}

      - name: Capture screenshot
        env:
          COMMENT_BODY: |
            ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cat /tmp/play.yml
          su - pptruser -c "node /pupptr-play/dist/index.js /tmp/play.yml"

      - name: Save screenshot
        id: saveScreenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: ${{ inputs.output }}

      - name: Set Output
        run: |
          echo "screenshot=$(echo ${{ inputs.output }})" >> $GITHUB_OUTPUT

      - name: Update PR's comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: "[screenshot archive](${{ steps.saveScreenshot.outputs.artifact-url }})"
          reactions: eyes

      - name: Github API Request
        uses: octokit/request-action@v2.2.0
        with:
          route: POST ${{ fromJson(steps.request.outputs.data).statuses_url }}
          state: ${{ job.status }}
          target_url: "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/${{ steps.saveScreenshot.outputs.artifact-id }}/zip"
          context: "Screenshot / ${{ github.workflow }} (artifact)"
        env:
          GITHUB_TOKEN: ${{ github.token }}
